#!/usr/bin/env bash

LOCK_FILE="/tmp/my_script.lock"

# Check if another instance is already running
if [ -e "$LOCK_FILE" ] && kill -0 $(cat "$LOCK_FILE"); then
  echo "Another instance is already running."
  exit 1
fi

# Create the lock file
echo $$ > "$LOCK_FILE"

speak(){
    piper --length_scale 1.2 --model\
      ~/.local/share/piper_model/en_US-lessac-medium.onnx \
      --output-raw | aplay -f S16_LE -c1 -r22050 -
}

if [ $# -eq 0 ]
  then
    # Core logic
    active_window=$(xdotool getactivewindow)

    if [[ $(xprop -id $active_window | grep WM_CLASS\(STRING\)) =~ "xst" ]]; then
        xdotool getactivewindow key ctrl+shift+c
    else
        xdotool getactivewindow key ctrl+c
    fi

    xclip -o -selection clipboard | speak
else
    echo "$@" | speak
fi

# Remove the lock file
rm "$LOCK_FILE"