# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b6ba1d4c-03b2-459c-94fc-ac232c6c7014";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/e678bd4c-6c50-45be-90c2-137d6258c028";

  # tlp is enabled by nixos-hardware.asus-rog-strix-g513im
  services.tlp.settings = {
    CPU_SCALING_GOVERNOR_ON_BAT="powersave";
    CPU_SCALING_GOVERNOR_ON_AC="ondemand";
    CPU_MAX_PERF_ON_AC=100;
    CPU_MAX_PERF_ON_BAT=50;

    # My laptop is always plugged in wherever I'm willing to use it, so I'll
    # value battery lifespan over runtime. Run `tlp fullcharge` to temporarily
    # force full charge.
    # @see https://linrunner.de/tlp/faq/battery.html#how-to-choose-good-battery-charge-thresholds
    START_CHARGE_THRESH_BAT0=60;
    STOP_CHARGE_THRESH_BAT0=70;
  };

  modules.hardware = {
    audio.enable = true;
    bluetooth.enable = true;
    nvidia.enable = true;
    microcontroller.enable = true;
    android.enable = true;
    fs = {
      enable = true;
    };
    sensors.enable = true;

    # benchmarking
    utilites.enable = true;
  };

  hardware = {
    xone.enable = true;  # Xbox controller support
    onlykey.enable = true;  # OnlyKey token support
  };

  services.asusd = {
    enable = true;
    asusdConfig = ''
      {
        "bat_charge_limit": 70
      }
    '';
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0429-8336";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/9177da30-8ca8-422d-9b18-4e129caafd12"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}