# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/454ecdd1-dfb4-4453-88b1-3b06d5412123";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C96B-3940";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/454ecdd1-dfb4-4453-88b1-3b06d5412123";
      fsType = "btrfs";
      options = [ "subvol=home" ];
      neededForBoot = true; # required to load ssh key with agenix early
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/454ecdd1-dfb4-4453-88b1-3b06d5412123";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/media" =
    { device = "/dev/disk/by-uuid/be2762fb-8138-445a-a32f-3ae007f6a4f5";
      fsType = "btrfs";
    };

  fileSystems."/var/lib/private/photoprism/originals" =
  { device = "${config.user.home}/Pictures/photos";
    options = [ "bind" ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}